name: "Build"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '*'
      - '!ci_test_*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
      - '!ci_test_*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: rustup target add aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu i686-unknown-linux-gnu powerpc-unknown-linux-gnu
      - run: RUSTFLAGS="-C target-feature=+neon" cargo build --target aarch64-unknown-linux-gnu
      - run: RUSTFLAGS="-C target-feature=+avx2" cargo build --target i686-unknown-linux-gnu
      - run: cargo build --target powerpc-unknown-linux-gnu
      - run: RUSTFLAGS="-C target-feature=+avx2" cargo build --target x86_64-unknown-linux-gnu

  tests:
    name: Tests
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  clippy_x86:
    name: Clippy x86 Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --all-features -- -D warnings

  clippy_x86_nightly:
    name: Clippy x86 Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - run: rustup component add clippy
      - run: cargo clippy --all-features -- -D warnings

  clippy_arm:
    name: Clippy ARM
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy -- -D warnings

  fuzz_arm:
    name: Fuzzing ARM
    runs-on: macos-latest
    strategy:
      matrix:
        feature: [ neon ]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install cargo-fuzz
      - run: cargo fuzz run dilation --no-default-features --features ${{ matrix.feature }} -- -max_total_time=10
      - run: cargo fuzz run dilation1d --no-default-features --features ${{ matrix.feature }} -- -max_total_time=10

  fuzz_x86_64:
    name: Fuzzing x86_64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [ sse, avx ]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install cargo-fuzz
      - run: cargo fuzz run dilation --no-default-features --features ${{ matrix.feature }} -- -max_total_time=12
      - run: cargo fuzz run dilation1d --no-default-features --features ${{ matrix.feature }} -- -max_total_time=5
